#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <hipl_format.h>
#include <time.h>
#include "useful3.h"
#include "wavefront.h"
#include "allocate.h"
#include "zv.h"
#include "error.h"

main(argc,argv)
int	argc;
char	**argv;
{
	int	JulianDay=0,direct_op=0,i,tau_flag=0,isotropic_flag;
	Lambda	lambda;
	FLOAT	tmp,sun_position[2],gamma,isotropic;
	Atmospheric_Inputs	atmospheric_inputs;
	char	*atmos_file,buffer[1000],skymap[1000],tau_file[1000],scale_height_lut_file[1000];
	OpticalDepth	*tau;
	Image_characteristics	skydata,scale_height_lut;
	char	*orig_name = "Lewis' Zibbordi & Voss Model : Sky Radiance Sequence";


	lambda.lambda_gap=1;	/* default step of 100nm */
	lambda.lambda_start=450.0;	/* nm */
	lambda.lambda_end=550.0;
	lambda.angres[0]=2.0;		/* angular resolution rows	*/
	lambda.angres[1]=2.0;		/* angular resolution cols	*/
	skydata.hd.rows=(int)(90.0/lambda.angres[0] + 0.5) + 1;
	skydata.hd.cols=(int)(360.0/lambda.angres[1] + 0.5) + 1;

	strcpy(skymap,"sky.hips");
	scale_height_lut_file[0]='\0';
	scale_height_lut.data.fdata=NULL;

	sun_position[0]=45.0;
	sun_position[1]=0.0;

	atmos_file=NULL;
	isotropic_flag=0;
	isotropic=0.0;

	atmospheric_inputs.altitude[0]=0.0;	/* ground */
	atmospheric_inputs.altitude[1]=1000;	/* sensor */
	atmospheric_inputs.altitude_flag=0;

	InitHeader(&skydata,orig_name,2,"","",PFFLOAT);
	update_header(&skydata.hd,argc,argv);

	for(i=1;i<argc;i++){
		if(strcmp(argv[i],"-skymap")==0){		/* op skymap filename */
			strcpy(skymap,argv[++i]);
		}else if(strcmp(argv[i],"-ground")==0){		/* ground height (km) */
			atmospheric_inputs.altitude_flag=1;
			atmospheric_inputs.altitude[0]=atof(argv[++i]);
		}else if(strcmp(argv[i],"-altitude")==0){		/* altitude of sensor (km) */
			atmospheric_inputs.altitude_flag=1;
			atmospheric_inputs.altitude[1]=atof(argv[++i]);
		}else if(strcmp(argv[i],"-DOY")==0){		/* op skymap filename */
			JulianDay=atoi(argv[++i]);
		}else if(strcmp(argv[i],"-direct")==0){		/* direct irrad to stdout */
			direct_op=1;
		}else if(strcmp(argv[i],"-tau")==0){		/* op tau data only */
			tau_flag=1;
		}else if(strcmp(argv[i],"-tau_op")==0){		/* op tau data only */
			tau_flag=1;
		}else if(strcmp(argv[i],"-tau_ip")==0){		/* ip tau data from stdin */
			tau_flag=2;
			strcpy(tau_file,argv[++i]);
		}else if(strcmp(argv[i],"-LUT")==0){		/* scale height data from LUT generated by program scale_heights */
			strcpy(scale_height_lut_file,argv[++i]);
			mmap_read_hips_image(scale_height_lut_file,&(scale_height_lut.hd),&(scale_height_lut.data));
		}else if(strcmp(argv[i],"-LSL")==0){		/* ip tau data from  tau_file*/
			tau_flag=2;
			strcpy(tau_file,argv[++i]);
		}else if(strcmp(argv[i],"-angres")==0){		/* degrees */
			lambda.angres[0]=atof(argv[++i]);
			lambda.angres[1]=atof(argv[++i]);
			skydata.hd.rows=(int)(90.0/lambda.angres[0] + 0.5) + 1;
			skydata.hd.cols=(int)(360.0/lambda.angres[1] + 0.5) + 1;
		}else if(strcmp(argv[i],"-sun")==0){
			sun_position[0]=90.0 - atof(argv[++i]);	/* read in solar elevation */
			sun_position[1]=atof(argv[++i]);	/* read in solar azimuth */
		}else if(strcmp(argv[i],"-atmosphere")==0){
			atmos_file=buffer;
			strcpy(atmos_file,argv[++i]);
		}else if(strcmp(argv[i],"-isotropic")==0){
			isotropic=atof(argv[++i]);
			isotropic_flag=1;
		}else if(strcmp(argv[i],"-lambda")==0){
			lambda.lambda_start=atof(argv[++i]);
			lambda.lambda_end=atof(argv[++i]);
			tmp=atof(argv[i+1]);
			lambda.lambda_gap=MAX(tmp,lambda.lambda_gap);
		}
	}

	lambda.no_of_wavebands = (int)((lambda.lambda_end - lambda.lambda_start)/lambda.lambda_gap + 0.5) + 1;

	skydata.hd.num_frame=lambda.no_of_wavebands;

	if(!(tau=(OpticalDepth *)calloc(lambda.no_of_wavebands,sizeof(OpticalDepth))))
		error1("tau:\terror in core allocation");

	if(!tau_flag!=2){	/* generate tau data */
		read_atmospheric_input_data(atmos_file,&lambda,&atmospheric_inputs);

		calculate_optical_depth(JulianDay,tau,&lambda,&atmospheric_inputs,&scale_height_lut);

		if(tau_flag==1 && scale_height_lut.data.fdata==NULL){
			output_tau_data(tau,&lambda,&atmospheric_inputs);
			exit(1);
		}
	}else{			/* read tau data */
		read_tau_data(JulianDay,tau_file,atmos_file,&lambda,&atmospheric_inputs,tau);
	}

	mmap_write_hips_image_no_free(skymap,&skydata.hd,&skydata.data,argc,argv,0);

	create_skymap(direct_op,sun_position,&lambda,&skydata,&(atmospheric_inputs),tau,JulianDay,&scale_height_lut,isotropic_flag,isotropic);
		

}
